[package]
name = "contain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-random = "0.1.17"
hex = "0.4.3"
home = "0.5.9"
rand = "0.8.5"
rust-crypto = "0.2.36"
